### ISSUE TITLE
Deploy storyboard to GitHub pages

### ISSUE THREAD

**Issue by bram209** [tenzir/ui-component-library#33]
Hi, first of all, looks like a solid ui component library, excited about it's future :)

Would it be possible to deploy the storyboard to GitHub pages, so that people can easily use it as a showcase without having to pull the repository and run it locally?

https://storybook.js.org/docs/basics/exporting-storybook/

**Comment by rolandpeelen** [comment]
Hi!

Thank you for your kind words and thanks for the suggestion. That's a great idea!
We're currently looking into this, and expect to have this up-and-running in a few :)

**Comment by 0ortmann** [comment]
@bram209 we addressed your request with [PR#38](https://github.com/tenzir/ui-component-library/pull/38) :)
